name: Build and Deploy
on:
  push:
    branches:
      - barba
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Node v14
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '14.x'

      - name: Install and Build ğŸ”§
        run: |
          npm install pnpm
          npx pnpm install
          npx pnpm run build

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: barba
          FOLDER: /docs
          CLEAN: true # Automatically remove deleted files from the deploy branch
